# Generated by Django 2.2.5 on 2019-09-19 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_url', models.URLField(help_text='Please enter the url of the video from youtube or other sources')),
                ('video_description', models.TextField()),
                ('date', models.DateField()),
            ],
        ),
    ]
