# Generated by Django 2.2.5 on 2019-09-19 09:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0003_auto_20190919_1452'),
    ]

    operations = [
        migrations.CreateModel(
            name='BigBanner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='banner/')),
                ('added_date', models.DateField(default=django.utils.timezone.now)),
                ('valied_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='SmallBanner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='banner/')),
                ('company_name', models.CharField(blank=True, max_length=200, null=True)),
                ('added_date', models.DateField(default=django.utils.timezone.now)),
                ('valied_date', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='Banner',
        ),
    ]
