# Generated by Django 2.2.5 on 2019-09-19 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0007_auto_20190919_1531'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='thumbnail_image',
            field=models.ImageField(blank=True, null=True, upload_to='thumbnail/'),
        ),
    ]
