# Generated by Django 2.2.5 on 2019-09-27 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0008_video_thumbnail_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='video_caption',
            field=models.TextField(blank=True, null=True),
        ),
    ]
