# Generated by Django 2.2.5 on 2019-09-27 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0009_video_video_caption'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='recent',
            field=models.BooleanField(default=False, verbose_name='Do you want this video to display in recent section?'),
        ),
    ]
