# Generated by Django 2.2.5 on 2019-09-29 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0011_remove_video_recent'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='most_viewed',
            field=models.BooleanField(default=False, verbose_name='Do you want this video to display in most viewed section?'),
        ),
    ]
