# Generated by Django 2.2.5 on 2019-10-01 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0012_video_most_viewed'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='recommend',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Do you want this video to display in most viewed section?'),
        ),
    ]
