# Generated by Django 2.2.5 on 2019-10-01 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0013_video_recommend'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='recommend',
            field=models.BooleanField(default=False, verbose_name='Do you want this video to display in recommend section?'),
        ),
    ]
