# Generated by Django 2.2.5 on 2019-10-01 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0014_auto_20191001_1256'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='most_viewed',
        ),
    ]
