# Generated by Django 2.2.5 on 2019-10-01 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0016_video_latest'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='featured',
            field=models.BooleanField(default=False, verbose_name='Do you want this video to display in featured section?'),
        ),
    ]
