# Generated by Django 2.2.5 on 2019-10-03 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0019_smallbanner_company_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bigbanner',
            name='company_link',
            field=models.URLField(help_text='Please enter the url of company'),
        ),
        migrations.AlterField(
            model_name='bigbanner',
            name='company_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='bigbanner',
            name='main_image',
            field=models.ImageField(help_text='Image size: width=1024px height=77px', upload_to='banner/'),
        ),
        migrations.AlterField(
            model_name='smallbanner',
            name='company_link',
            field=models.URLField(help_text='Please enter the url of company'),
        ),
        migrations.AlterField(
            model_name='smallbanner',
            name='company_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='smallbanner',
            name='image',
            field=models.ImageField(help_text='Image size: width=1024px height=500px', upload_to='banner/'),
        ),
    ]
