# Generated by Django 2.2.6 on 2019-10-05 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0021_aboutus'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
