# Generated by Django 2.2.5 on 2019-11-03 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0022_category_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
